#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:
        
    # FACTS #######################################################################

    - name: create nextcloud state
      shell: |
        echo "1" > /opt/seedbox/status/onlyoffice

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'sub' variable"
      set_fact:
        sub_enabled: "{{ true if not(
            (sub.onlyoffice is undefined)
            or
            (sub.onlyoffice is none)
            or
            (sub.onlyoffice | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.nextcloud if sub_enabled else 'nextcloud'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'onlyoffice'
      
    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}'



#####################OnllyOffice###############################################################

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.onlyoffice if sub_enabled else 'onlyoffice'}}"
      when: cloudflare_enabled

    - name: 'Adding Traefik'
      set_fact:
        off_labels:
          traefik.enable: 'true'
          traefik.http.routers.office-rtr.entrypoints: 'https'
          traefik.http.routers.office-rtr.rule: 'HostSNI(`{{sub.onlyoffice if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.office-rtr.tls: 'true'
          traefik.http.routers.office-rtr.service: 'office-svc'
          traefik.http.services.office-svc.loadbalancer.server.port: '80'
          traefik.http.services.office-svc.loadbalancer.passhostheader: 'true'
          traefik.http.routers.office-rtr.middlewares: 'office-sslheaders'
          traefik.http.middlewares.office-sslheaders.headers.customrequestheaders.X-Forwarded-Proto: 'https'

    - name: Create and start office container
      docker_container:
        name: office
        image: 'onlyoffice/documentserver:latest'
        pull: yes
        interactive: True
        tty: true
        networks:
          - name: traefik_proxy
        restart_policy: unless-stopped
        state: started
        labels: '{{off_labels}}'

    - name: add resume file
      shell: |
        echo "{{pgrole}}-{{sub.onlyoffice if sub_enabled else pgrole}}.{{user.domain}}" >> /opt/temp.txt

    - name: create onlyoffice state
      shell: |
        echo "2" > /opt/seedbox/status/onlyoffice

